<?php
require_once '../../config/database.php';
require_once '../../config/auth.php';
require_once '../../config/roles.php';

$database = new Database();
$db = $database->getConnection();
$auth = new Auth($db);

if (!$auth->isLoggedIn()) {
    header("Location: ../auth/login.php");
    exit();
}

$current_user = $auth->getCurrentUser();

// Check permission
if (!hasPermission($current_user['role'], 'reports', 'read')) {
    header("HTTP/1.0 403 Forbidden");
    exit();
}

$report_id = intval($_GET['id'] ?? 0);
if (!$report_id) {
    header("HTTP/1.0 404 Not Found");
    exit();
}

// Fetch report details
$query = "SELECT r.*, p.name as project_name, p.client_name, u.name as created_by_name
          FROM project_reports r 
          LEFT JOIN projects p ON r.project_id = p.id 
          LEFT JOIN users u ON r.created_by = u.id
          WHERE r.id = ?";
$stmt = $db->prepare($query);
$stmt->execute([$report_id]);
$report = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$report) {
    header("HTTP/1.0 404 Not Found");
    exit();
}

// Check if user can view this report
if ($current_user['role'] != 'admin' && $current_user['role'] != 'manager' && 
    $report['created_by'] != $current_user['id']) {
    header("HTTP/1.0 403 Forbidden");
    exit();
}

// Generate filename
$filename = 'Report_' . str_replace(' ', '_', $report['title']) . '_' . date('Y-m-d') . '.txt';

// Set headers for download
header('Content-Type: text/plain');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Content-Length: ' . strlen(generateReportContent($report)));

// Output report content
echo generateReportContent($report);

function generateReportContent($report) {
    $content = "=====================================\n";
    $content .= "       PROJECT REPORT\n";
    $content .= "=====================================\n\n";
    
    $content .= "Report Title: " . $report['title'] . "\n";
    $content .= "Report Type: " . ucfirst($report['report_type']) . " Report\n";
    $content .= "Project: " . $report['project_name'] . "\n";
    $content .= "Client: " . $report['client_name'] . "\n";
    $content .= "Report Date: " . date('F d, Y', strtotime($report['report_date'])) . "\n";
    $content .= "Created By: " . $report['created_by_name'] . "\n";
    $content .= "Created On: " . date('F d, Y H:i', strtotime($report['created_at'])) . "\n\n";
    
    $content .= "=====================================\n";
    $content .= "       REPORT CONTENT\n";
    $content .= "=====================================\n\n";
    
    $content .= $report['content'] . "\n\n";
    
    $content .= "=====================================\n";
    $content .= "   Generated by Interior Project Management System\n";
    $content .= "   " . date('F d, Y H:i:s') . "\n";
    $content .= "=====================================\n";
    
    return $content;
}
?>